#!/bin/sh
# Copyright (c) 2012-2013 National Instruments.
# All rights reserved.

[ "${VERBOSE}" != "no" ] && echo -n "Starting nicreatecpuacctgroups:"
mkdir -p /dev/cgroup/cpuacct
mount -t cgroup -ocpuacct none /dev/cgroup/cpuacct
cd /dev/cgroup/cpuacct
mkdir LabVIEW_Timed-Structures_group
mkdir LabVIEW_Time-Critical_group
mkdir ISR_group
mkdir other_group

while read TASK
do
	echo $TASK > "./other_group/tasks" 2> /dev/null 
	# cgroup behavior as of 3.10 kernel has been altered 
	# such that certain tasks cannot be assigned to any cgroup.
	# Because of this change an error for trying to assign those
	# tasks can be ignored in this loop and the following loop. 
done < "tasks"

# If we cannot move a task from the root cpuset, that task is softirq
# or related to system timer task
while read TASK
do
	echo $TASK > "./ISR_group/tasks" 2> /dev/null
done < "/dev/cgroup/cpuset/tasks"

chown -R lvuser:ni /dev/cgroup/cpuacct
[ "${VERBOSE}" != "no" ] && echo "done"
