#!/bin/sh
# Copyright (c) 2012-2023 National Instruments.
# All rights reserved.

[ "${VERBOSE}" != "no" ] && echo -n "Starting nicreatecpusets:"

MOUNT_POINT="/dev/cgroup/cpuset"
EXISTING_MOUNT_POINT=$(grep -sE "^cgroup" /proc/mounts | grep -m 1 "cpuset" | awk '{print $2}')

mkdir -p "$MOUNT_POINT"
if [ -d "$EXISTING_MOUNT_POINT" ]; then
	mount --bind "$EXISTING_MOUNT_POINT" "$MOUNT_POINT"
else
	mount -t cpuset none "$MOUNT_POINT"
fi
cd "$MOUNT_POINT"

mkdir LabVIEW_ScanEngine_set
mkdir LabVIEW_tl_set
mkdir system_set

#cpus and mems cannot be empty while tasks are added to tasks file
#in a cpuset
cat cpuset.cpus > ./system_set/cpuset.cpus
cat cpuset.mems > ./system_set/cpuset.mems

cat cpuset.cpus > ./LabVIEW_tl_set/cpuset.cpus
cat cpuset.mems > ./LabVIEW_tl_set/cpuset.mems

cat cpuset.cpus > ./LabVIEW_ScanEngine_set/cpuset.cpus
cat cpuset.mems > ./LabVIEW_ScanEngine_set/cpuset.mems

while read TASK
do
	echo $TASK > "./system_set/tasks" 2> /dev/null
	# Following system tasks are specifically affined to run on a core
	# and cannot be moved. So, the above line does thrown
	# an error for these tasks and those can be ignored.
	# kworker|ksoftirqd|posixcputmr|migration
done < "tasks"

chown -R lvuser:ni /dev/cgroup/cpuset
[ "${VERBOSE}" != "no" ] && echo "done"
